### ISSUE TITLE
Chrome Browser only: Cursor jumps to position 0:0 with each keystroke

### ISSUE THREAD

**Issue by klauswr** [sinnlabs/zk-codemirror#4]
This happens only in Chrome (Version 63.0.3239.84) - Firefox and IE is fine: 

whenever you enter a character (wherever you want) the cursor always jumps back to the top left corner. 

This was already the case with previous version 0.1!

**Comment by nsa-a1** [comment]
Fixed in https://github.com/sinnlabs/zk-codemirror/commit/7a00fefcfd472810bbedea1892953f75884485cd

**Comment by nsa-a1** [comment]
you can use the sonatype repo (https://oss.sonatype.org/content/repositories/releases) for the new version.
README.md file will be updated after synchronization with Maven's repository. This may take a while.

**Comment by klauswr** [comment]
Tested: OK (Thanks for the quick fix)
