### ISSUE TITLE
Sql support

### ISSUE THREAD

**Issue by mpizeli** [sinnlabs/zk-codemirror#8]
Hello,
Excelent work. Any change to add SQL support please ?

**Comment by nsa-a1** [comment]
Hi, yep it is possible. Do you need an exact dialect?

**Comment by mpizeli** [comment]
Thanks a lot for accepting it and work for it.  Although i use mariadb/mysql i dont think a dialog is nessecary

**Comment by nsa-a1** [comment]
Add sql support. Version 0.7

**Comment by mpizeli** [comment]
wow that was fast. thanks
